apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-backend
  namespace: marline-expensy
  labels:
    app: expensy-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expensy-backend
  template:
    metadata:
      labels:
        app: expensy-backend
    spec:
      containers:
        - name: expensy-api
          image: marlinejohn/expensy-backend:latest
          ports:
            - containerPort: 8706
          env:
            - name: DATABASE_URI
              value: "mongodb://root:example@mongo:27017"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "someredispassword"

---
apiVersion: v1
kind: Service
metadata:
  name: expensy-backend
spec:
  selector:
    app: expensy-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8706
  type: LoadBalancer
