apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-frontend
  namespace: marline-expensy
  labels:
    app: expensy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expensy-frontend
  template:
    metadata:
      labels:
        app: expensy-frontend
    spec:
      containers:
        - name: expensy-frontend
          image: marlinejohn/expensy-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://aa21efd8031bf4c07a19d92e8c39243d-522384215.eu-north-1.elb.amazonaws.com"

---
apiVersion: v1
kind: Service
metadata:
  name: expensy-frontend
  namespace: marline-expensy
spec:
  selector:
    app: expensy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
